- name: Install LAMP Stack
  hosts: webserver
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Install MySQL
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Install PHP
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Enable and start Apache
      ansible.builtin.systemd:
        name: apache2
        enabled: true
        state: started

    - name: Enable and start MySQL
      ansible.builtin.systemd:
        name: mysql
        enabled: true
        state: started
